### ISSUE TITLE
Directory watching on Windows doesn't work

### ISSUE THREAD

**Issue by helikopterodaktyl** [WebFreak001/FSWatch#15]
Code like this:

`	
watcher = FileWatch("C:/test/", true);
while (1) {
	foreach (event; watcher.getEvents())
	{
		writeln(event.path);
	}
}`

when ran and creating/deleting/modifying files in C:\test\ directory, no paths get written to stdout

**Comment by WebFreak001** [comment]
works fine here under windows 10 VM

**Comment by helikopterodaktyl** [comment]
Interesting. Doesn't work with my Windows 10. I am using the 0.3.0 version of the library. Watching a file works, just the directory that doesn't.

**Comment by WebFreak001** [comment]
having the folder there before starting and after starting doesn't make a difference. Have you tried exactly running your example code and not in the application?

**Comment by helikopterodaktyl** [comment]
Well... I restarted everything, IDE and all, rebuilt my app from scratch and it's working now. I have no idea why it didn't work before...

**Comment by helikopterodaktyl** [comment]
Ahhh. I see the issue. I don't know what is causing it, perhaps some threading related issue? If the FileWatch variable is a global, it doesn't work.

doesn't work:
```
FileWatch watcher;
void main() { watcher = FileWatch(... }

```
works:
`void main() { FileWatch watcher = FileWatch(... }`

Is this expected? I don't see why would one work, but not another.

**Comment by WebFreak001** [comment]
hm there is some destruction code, does it work if you comment out line 106 (`CloseHandle(pathHandle);`) for testing purposes?

**Comment by helikopterodaktyl** [comment]
```
void main() { FileWatch watcher; watcher = FileWatch(... }
```

declaring it like this also doesn't work. Works only if watcher is assigned during the declaration.

let me check

**Comment by WebFreak001** [comment]
as workaround try `FileWatch* watcher; watcher = new FileWatch(...);`

**Comment by helikopterodaktyl** [comment]
Yes, the pointer works. Is this some obvious D thing that I am missing? I don't see what difference would it make.

**Comment by WebFreak001** [comment]
have you tried commenting the code I told you to to see if it works without pointer then?

**Comment by helikopterodaktyl** [comment]
Yes, doesn't seem to have an effect :(

**Comment by WebFreak001** [comment]
uh you have used the exact code you have initially posted + a declaration right? I don't really want to boot up my VM again...

If commenting that line doesn't change it I don't really know what could be causing it

**Comment by helikopterodaktyl** [comment]
Yes, exact code. Oh well, the pointer works for me, so I consider it non-issue.

**Comment by WebFreak001** [comment]
with v0.5.0 that assignment issue should be fixed too
