### ISSUE TITLE
Assigning FileWatch struct failing in dmd v2.086.0

### ISSUE THREAD

**Issue by SrMordred** [WebFreak001/FSWatch#19]
With error:
` Error: cannot modify struct instance watcher of type FileWatch because it contains const or immutable members`

(It´s suppose to be possible?)
https://github.com/WebFreak001/FSWatch/blob/63b46f971247596da23dceb3007793e1aff254ae/source/fswatch.d#L693

**Comment by WebFreak001** [comment]
uh does it work if you change the `const string path` to `string path`?

**Comment by SrMordred** [comment]
Probably yes, I just wondered if this was a design choice from the beginning 
( and the strange fact that only now on this dmd version the error appeared )

**Comment by WebFreak001** [comment]
The path is just informational and not reassignable as it won't update the underlying handles. It should only  prevent that and nothing else.

**Comment by WebFreak001** [comment]
fixed with f8463b3 (should be 0.5.0 in a minute)
